import { UCServiceItemData } from "@/components/UCServiceCard";

// 1. AC SERVICES SUB-CATEGORIES & PACKAGES
export const AC_SUBCATEGORIES = [
  { id: "annual-plan", labelEn: "Annual plan", labelTe: "వార్షిక ప్లాన్" },
  { id: "service", labelEn: "Service & Jet Wash", labelTe: "సర్వీస్ & జెట్ వాష్" },
  { id: "repair-gas", labelEn: "Repair & Gas Refill", labelTe: "రిపేర్ & గ్యాస్ రీఫిల్" },
  { id: "install-shift", labelEn: "Install & Relocation", labelTe: "ఇన్‌స్టాల్ & షిఫ్టింగ్" },
] as const;

export const AC_SERVICE_ITEMS: UCServiceItemData[] = [
  {
    id: "ac-annual-2times",
    titleEn: "Annual plan (2 times/year)",
    titleTe: "వార్షిక ప్లాన్ (సంవత్సరానికి 2 సార్లు)",
    price: 798,
    originalPrice: 1198,
    durationEn: "2 visits / yr",
    durationTe: "సంవత్సరానికి 2 విజిట్లు",
    rating: "4.73",
    reviews: "65k",
    optionsCount: "14 options",
    inclusionsEn: [
      "Get 1st deep foam-jet service now. Choose 2nd service anytime in 2026",
      "Applicable for both window or split ACs",
      "Includes complete gas pressure check & drain pipe flush",
      "Priority pro dispatch in Nellore within 30 mins",
    ],
    inclusionsTe: [
      "మొదటి ఫోమ్ జెట్ సర్వీస్ ఇప్పుడే తీసుకోండి. 2వ సర్వీస్ 2026లో ఎప్పుడైనా పొందండి",
      "విండో లేదా స్ప్లిట్ ఏసీ రెండింటికీ వర్తిస్తుంది",
      "పూర్తి గ్యాస్ ప్రెజర్ చెక్ మరియు డ్రెయిన్ పైప్ వాష్ ఉచితం",
      "నెల్లూరులో 30 నిమిషాల్లో ప్రయారిటీ టెక్నీషియన్ విజిట్",
    ],
    exclusionsEn: ["Major spare parts like compressor replacement"],
    exclusionsTe: ["కంప్రెసర్ వంటి భారీ స్పేర్ పార్ట్స్ మినహాయింపు"],
    imageSrc: "/images/service-ac-annual.jpg",
    category: "ac",
    subcategory: "annual-plan",
  },
  {
    id: "ac-foam-jet-1ac",
    titleEn: "Foam-jet AC service (1 AC)",
    titleTe: "ఫోమ్-జెట్ ఏసీ సర్వీస్ (1 AC)",
    price: 599,
    originalPrice: 699,
    durationEn: "45 mins",
    durationTe: "45 నిమిషాలు",
    rating: "4.86",
    reviews: "1.4k",
    badge: "Free gas check",
    optionsCount: "7 options",
    inclusionsEn: [
      "Applicable for both window or split ACs",
      "Indoor unit deep cleaning with foam & jet spray",
      "Waterproof funnel jacket to protect room walls & floor",
      "Outdoor condenser unit washed & cleaned",
      "15-day cooling & leak warranty included",
    ],
    inclusionsTe: [
      "విండో లేదా స్ప్లిట్ ఏసీ రెండింటికీ వర్తిస్తుంది",
      "ఫోమ్ & హై-ప్రెజర్ వాటర్ జెట్‌తో ఇండోర్ యూనిట్ డీప్ క్లీనింగ్",
      "గోడలు, ఫ్లోర్ పాడవకుండా స్పెషల్ వాటర్‌ప్రూఫ్ జాకెట్",
      "అవుట్‌డోర్ కండెన్సర్ యూనిట్ శుభ్రం చేయడం",
      "15 రోజుల ఉచిత కూలింగ్ & లీక్ వారంటీ",
    ],
    exclusionsEn: ["Gas refilling or spare parts replacement"],
    exclusionsTe: ["గ్యాస్ రీఫిల్ లేదా స్పేర్ పార్ట్స్"],
    imageSrc: "/images/service-ac-foamjet.jpg",
    category: "ac",
    subcategory: "service",
  },
  {
    id: "ac-foam-jet-2acs",
    titleEn: "Foam-jet service (2 ACs)",
    titleTe: "ఫోమ్-జెట్ సర్వీస్ (2 ACs)",
    price: 1198,
    originalPrice: 1398,
    durationEn: "2 hrs",
    durationTe: "2 గంటలు",
    rating: "4.77",
    reviews: "15k",
    badge: "Free gas check",
    optionsCount: "₹599/AC",
    inclusionsEn: [
      "Applicable for both window or split ACs",
      "Indoor unit deep cleaning with foam & jet spray for 2 ACs",
      "Waterproof jacket for mess-free service",
      "Outdoor unit jet wash + gas pressure test",
    ],
    inclusionsTe: [
      "2 ఏసీలకు ఫోమ్ మరియు హై ప్రెజర్ జెట్ వాష్",
      "వాటర్‌ప్రూఫ్ జాకెట్‌తో గది పరిశుభ్రంగా ఉంటుంది",
      "అవుట్‌డోర్ యూనిట్ ప్రెజర్ క్లీనింగ్",
      "15 రోజుల సర్వీస్ వారంటీ",
    ],
    imageSrc: "/images/service-ac-2pack.jpg",
    category: "ac",
    subcategory: "service",
  },
  {
    id: "ac-foam-jet-3acs",
    titleEn: "Foam-jet service (3 ACs)",
    titleTe: "ఫోమ్-జెట్ సర్వీస్ (3 ACs)",
    price: 1749,
    originalPrice: 2097,
    durationEn: "3 hrs",
    durationTe: "3 గంటలు",
    rating: "4.80",
    reviews: "8.2k",
    badge: "Free gas check",
    optionsCount: "₹583/AC",
    inclusionsEn: [
      "Deep foam jet wash for 3 AC units",
      "Save up to ₹348 compared to individual bookings",
      "Full condenser and blower cleaning",
    ],
    inclusionsTe: [
      "3 ఏసీలకు పూర్తి ఫోమ్ జెట్ వాష్",
      "విడివిడిగా బుక్ చేయడం కంటే ₹348 ఆదా",
      "15 రోజుల ఉచిత కూలింగ్ గ్యారెంటీ",
    ],
    imageSrc: "/images/service-ac-3pack.jpg",
    category: "ac",
    subcategory: "service",
  },
  {
    id: "ac-jet-wash-window",
    titleEn: "Window AC Deep Jet Wash",
    titleTe: "విండో ఏసీ డీప్ జెట్ వాష్",
    price: 499,
    originalPrice: 599,
    durationEn: "45 mins",
    durationTe: "45 నిమిషాలు",
    rating: "4.81",
    reviews: "820",
    inclusionsEn: [
      "Complete front grill and filter wash",
      "Coil and fan blade pressure cleaning",
      "Electrical box check & performance test",
    ],
    inclusionsTe: [
      "ఫ్రంట్ గ్రిల్ & ఫిల్టర్ల పూర్తి వాష్",
      "కాయిల్ & ఫ్యాన్ బ్లేడ్ ప్రెజర్ క్లీనింగ్",
      "కూలింగ్ పనితీరు పరిశీలన",
    ],
    imageSrc: "/images/service-ac-window.jpg",
    category: "ac",
    subcategory: "service",
  },
  {
    id: "ac-anti-rust-coating",
    titleEn: "Anti-Rust Coil Protective Coating",
    titleTe: "కాయిల్ రక్షణ యాంటీ-రస్ట్ కోటింగ్",
    price: 399,
    originalPrice: 499,
    durationEn: "30 mins",
    durationTe: "30 నిమిషాలు",
    rating: "4.79",
    reviews: "450",
    inclusionsEn: [
      "Specialized protective acrylic spray on condenser & cooling coils",
      "Prevents gas leaks and corrosion from coastal salty Nellore air",
      "Increases AC coil lifespan significantly",
    ],
    inclusionsTe: [
      "కండెన్సర్ కాయిల్స్‌పై ప్రత్యేక యాక్రిలిక్ స్ప్రే",
      "సముద్రపు ఉప్పు గాలి వల్ల వచ్చే తుప్పు & గ్యాస్ లీకేజ్ నివారణ",
      "ఏసీ కాయిల్స్ మన్నికను పెంచుతుంది",
    ],
    imageSrc: "/images/service-ac-antirust.jpg",
    category: "ac",
    subcategory: "service",
  },
  {
    id: "ac-repair-inspection",
    titleEn: "AC repair",
    titleTe: "ఏసీ రిపేర్ & చెకప్",
    price: 299,
    originalPrice: 399,
    durationEn: "30 mins",
    durationTe: "30 నిమిషాలు",
    rating: "4.73",
    reviews: "488k",
    optionsCount: "1 option",
    inclusionsEn: [
      "Complete check-up to identify issues before repair",
      "Cooling temperature & amperage test with digital multimeter",
      "Inspection fee adjusted if you approve repairs",
    ],
    inclusionsTe: [
      "రిపేర్‌కు ముందు సమస్యను గుర్తించడానికి సమగ్ర తనిఖీ",
      "కూలింగ్ టెంపరేచర్ & ఆంపియర్ టెస్ట్",
      "రిపేర్ చేయిస్తే ఈ ఇన్‌స్పెక్షన్ ఫీజు మినహాయించబడుతుంది",
    ],
    imageSrc: "/images/service-ac-repair.jpg",
    category: "ac",
    subcategory: "repair-gas",
  },
  {
    id: "ac-gas-refill-check",
    titleEn: "Gas refill & check-up",
    titleTe: "గ్యాస్ రీఫిల్ & చెకప్",
    price: 1999,
    originalPrice: 2499,
    durationEn: "2 hrs 30 mins",
    durationTe: "2 గంటల 30 నిమిషాలు",
    rating: "4.77",
    reviews: "1.3M",
    inclusionsEn: [
      "High-pressure nitrogen leak test before refill",
      "100% pure virgin refrigerant gas (R32 / R410A / R22)",
      "Precision digital weighing scale refill",
      "30-day gas leak warranty included",
    ],
    inclusionsTe: [
      "గ్యాస్ నింపే ముందు నైట్రోజన్ లీక్ టెస్ట్",
      "100% స్వచ్ఛమైన ఒరిజినల్ గ్యాస్ రీఫిల్",
      "డిజిటల్ స్కేల్ ద్వారా ఖచ్చితమైన బరువుతో నింపడం",
      "30 రోజుల పూర్తి గ్యాస్ వారంటీ",
    ],
    imageSrc: "/images/service-ac-gasrefill.jpg",
    category: "ac",
    subcategory: "repair-gas",
  },
  {
    id: "ac-water-leak-fix",
    titleEn: "Water leakage & drain fix",
    titleTe: "వాటర్ లీకేజ్ & డ్రెయిన్ క్లీనింగ్",
    price: 349,
    originalPrice: 449,
    durationEn: "30 mins",
    durationTe: "30 నిమిషాలు",
    rating: "4.80",
    reviews: "210",
    inclusionsEn: [
      "Drain tray and drain pipe unclogging with pressure flush",
      "Indoor back-tray alignment to stop water drops on wall",
      "15-day leak warranty",
    ],
    inclusionsTe: [
      "డ్రెయిన్ ట్రే & పైపులోని చెత్తను క్లీన్ చేసి నీటి ప్రవాహం సరిచేయడం",
      "గోడపై నీళ్లు కారకుండా ఇండోర్ యూనిట్ అలైన్‌మెంట్",
      "15 రోజుల లీక్ వారంటీ",
    ],
    imageSrc: "/images/service-ac-drainfix.jpg",
    category: "ac",
    subcategory: "repair-gas",
  },
  {
    id: "ac-installation",
    titleEn: "AC installation",
    titleTe: "ఏసీ ఇన్‌స్టాలేషన్",
    price: 899,
    originalPrice: 1199,
    durationEn: "1 hr 30 mins",
    durationTe: "1 గంట 30 నిమిషాలు",
    rating: "4.73",
    reviews: "523k",
    optionsCount: "2 options",
    inclusionsEn: [
      "Installation of indoor & outdoor with core drilling",
      "Heavy-duty outdoor bracket mounting with spirit-level balancing",
      "Vacuum pump air-purging & cooling verification",
    ],
    inclusionsTe: [
      "ఇండోర్ & అవుట్‌డోర్ యూనిట్ల ప్రొఫెషనల్ ఫిట్టింగ్",
      "స్ప్రిట్ లెవల్ బ్యాలెన్సింగ్‌తో అవుట్‌డోర్ బ్రాకెట్ మౌంటింగ్",
      "వాక్యూమ్ పంప్ ద్వారా పైపులలోని గాలి తొలగించి కూలింగ్ టెస్ట్",
    ],
    imageSrc: "/images/service-ac-install.jpg",
    category: "ac",
    subcategory: "install-shift",
  },
  {
    id: "ac-uninstallation",
    titleEn: "AC uninstallation",
    titleTe: "ఏసీ అన్‌ఇన్‌స్టాలేషన్",
    price: 499,
    originalPrice: 599,
    durationEn: "45 mins",
    durationTe: "45 నిమిషాలు",
    rating: "4.75",
    reviews: "41k",
    optionsCount: "2 options",
    inclusionsEn: [
      "Zero gas loss pump-down procedure to lock gas in condenser",
      "Safe dismounting of indoor unit, outdoor unit & copper pipe",
      "Neat wire rolling and packaging",
    ],
    inclusionsTe: [
      "గ్యాస్ వృథా కాకుండా పంప్-డౌన్ లాకింగ్ పద్ధతి",
      "ఇండోర్, అవుట్‌డోర్ & కాపర్ పైపులను సురక్షితంగా విప్పడం",
      "వైర్లను భద్రంగా చుట్టి ఇవ్వడం",
    ],
    imageSrc: "/images/service-ac-uninstall.jpg",
    category: "ac",
    subcategory: "install-shift",
  },
  {
    id: "ac-complete-shifting",
    titleEn: "Complete AC Shifting (Within Nellore)",
    titleTe: "ఏసీ కంప్లీట్ షిఫ్టింగ్ (నెల్లూరులో)",
    price: 1299,
    originalPrice: 1699,
    durationEn: "2 hrs 30 mins",
    durationTe: "2 గంటల 30 నిమిషాలు",
    rating: "4.82",
    reviews: "180",
    optionsCount: "1 option",
    inclusionsEn: [
      "Zero gas loss uninstallation at old home",
      "Safe transport & complete re-installation at new site",
      "Vacuum test & complete cooling check",
    ],
    inclusionsTe: [
      "పాత ఇంట్లో సురక్షితంగా విప్పి గ్యాస్ లాక్ చేయడం",
      "కొత్త ప్రదేశానికి తరలించి తిరిగి ఫిట్టింగ్ చేయడం",
      "కూలింగ్ టెస్ట్ పూర్తి చేయడం",
    ],
    imageSrc: "/images/service-ac-shifting.jpg",
    category: "ac",
    subcategory: "install-shift",
  },
];

// 2. PEST CONTROL SUB-CATEGORIES & PACKAGES (Screenshots: Cockroach, Termite, Bedbugs, Ants)
export const PEST_SUBCATEGORIES = [
  { id: "cockroach", labelEn: "Cockroach Control", labelTe: "బొద్దింకలు" },
  { id: "termite", labelEn: "Termite Control", labelTe: "చెదలు నివారణ" },
  { id: "bedbugs-ants", labelEn: "Ants & Bed Bugs", labelTe: "నల్లులు & చీమలు" },
] as const;

export const PEST_SERVICE_ITEMS: UCServiceItemData[] = [
  // COCKROACH - KITCHEN / BATHROOM (Screenshot 1)
  {
    id: "pest-cockroach-utensils-included",
    titleEn: "Cockroach control (Includes utensil removal)",
    titleTe: "బొద్దింకల నివారణ (మేమే సామాన్లు తీసి పెడతాం)",
    price: 1249,
    originalPrice: 1499,
    durationEn: "1 hr 15 mins",
    durationTe: "1 గంట 15 నిమిషాలు",
    rating: "4.78",
    reviews: "168k",
    optionsCount: "6 options",
    inclusionsEn: [
      "Treatment will be completed in 2 visits with 2 weeks of gap",
      "We'll remove kitchen utensils before the service begins and neatly replace them",
      "Herbal Bayer gel baiting in all drawer hinges and crevices",
      "Drain pipe treatment to stop insects from sewer lines",
      "60 days warranty with free revisit",
    ],
    inclusionsTe: [
      "2 వారాల వ్యవధిలో 2 విజిట్లలో చికిత్స పూర్తి చేయబడుతుంది",
      "సర్వీస్‌కు ముందు వంటగది సామాన్లను మేమే తీసి పక్కన పెడతాం",
      "క్యాబినెట్లు, సొరుగులలో హెర్బల్ బేయర్ జెల్ చికిత్స",
      "డ్రెయిన్ పైపుల ద్వారా పురుగులు రాకుండా రక్షణ",
      "60 రోజుల ఉచిత రీ-విజిట్ వారంటీ",
    ],
    imageSrc: "/images/service-pest-general.jpg",
    category: "pest",
    subcategory: "cockroach",
  },
  {
    id: "pest-cockroach-no-utensils",
    titleEn: "Cockroach control (no utensil removal)",
    titleTe: "బొద్దింకల నివారణ (సామాన్లు తీయక్కర్లేదు)",
    price: 999,
    originalPrice: 1199,
    durationEn: "45 mins",
    durationTe: "45 నిమిషాలు",
    rating: "4.80",
    reviews: "97k",
    optionsCount: "6 options",
    inclusionsEn: [
      "Treatment will be completed in 2 visits with 2 weeks of gap",
      "Targeted gel dots applied behind appliances without touching kitchen utensils",
      "Excludes removal of utensils & objects before the service begins",
      "100% odorless and pet friendly",
      "60 days warranty included",
    ],
    inclusionsTe: [
      "2 వారాల వ్యవధిలో 2 విజిట్లలో చికిత్స పూర్తి చేయబడుతుంది",
      "సామాన్లు తీయకుండానే వాసన లేని చుక్కల జెల్ చికిత్స",
      "పిల్లలకు, పెంపుడు జంతువులకు 100% సురక్షితం",
      "60 రోజుల వారంటీ",
    ],
    imageSrc: "/images/service-pest-general.jpg",
    category: "pest",
    subcategory: "cockroach",
  },
  {
    id: "pest-apartment-cockroach",
    titleEn: "Apartment pest control (Utensil removal by customer)",
    titleTe: "అపార్ట్‌మెంట్ పెస్ట్ కంట్రోల్ (కస్టమర్ సామాన్లు సర్దాలి)",
    price: 1349,
    originalPrice: 1599,
    durationEn: "1 hr",
    durationTe: "1 గంట",
    rating: "4.80",
    reviews: "72k",
    optionsCount: "5 options",
    inclusionsEn: [
      "Spray treatment followed by gel treatment after 2 weeks",
      "Full apartment coverage: Kitchen, bathrooms, balconies, utility",
      "Excludes removal of utensils & objects before the service begins",
      "60 days warranty",
    ],
    inclusionsTe: [
      "స్ప్రే ట్రీట్‌మెంట్ తర్వాత 2 వారాలకు జెల్ ట్రీట్‌మెంట్",
      "పూర్తి అపార్ట్‌మెంట్: వంటగది, వాష్‌రూమ్‌లు, బాల్కనీ",
      "60 రోజుల వారంటీ",
    ],
    imageSrc: "/images/service-pest-v2.jpg",
    category: "pest",
    subcategory: "cockroach",
  },
  {
    id: "pest-bungalow-cockroach",
    titleEn: "Bungalow cockroach control (Utensil removal by customer)",
    titleTe: "బంగ్లా / విల్లా బొద్దింకల నివారణ",
    price: 2099,
    originalPrice: 2499,
    durationEn: "2 hrs",
    durationTe: "2 గంటలు",
    rating: "4.74",
    reviews: "7k",
    optionsCount: "4 options",
    inclusionsEn: [
      "Heavy-duty 2-visit spray & gel treatment for independent houses/villas",
      "Compound wall perimeter and drain inspection included",
      "60 days warranty",
    ],
    inclusionsTe: [
      "ఇండిపెండెంట్ ఇళ్ళు & విల్లాల కోసం హెవీ-డ్యూటీ ట్రీట్‌మెంట్",
      "కాంపౌండ్ డ్రెయిన్లు & బేస్‌మెంట్ పరిశీలన",
      "60 రోజుల వారంటీ",
    ],
    imageSrc: "/images/service-pest-general.jpg",
    category: "pest",
    subcategory: "cockroach",
  },

  // TERMITE CONTROL (Screenshots: Apartment vs Bungalow, Drill-Fill-Seal)
  {
    id: "pest-termite-apartment",
    titleEn: "Apartment termite control",
    titleTe: "అపార్ట్‌మెంట్ చెదలు నివారణ (Drill-Fill-Seal)",
    price: 3999,
    originalPrice: 4999,
    durationEn: "2 hrs",
    durationTe: "2 గంటలు",
    rating: "4.83",
    reviews: "18k",
    optionsCount: "5 options",
    inclusionsEn: [
      "Complete termite treatment for confined residential spaces",
      "Precision hole drilling at 1-foot intervals along skirting walls",
      "Chemical injection to create subterranean barrier and stop termite spread",
      "White cement sealing of all holes to restore wall aesthetic",
      "1-year service warranty included",
    ],
    inclusionsTe: [
      "అపార్ట్‌మెంట్ల కోసం ప్రత్యేక చెదలు నివారణ",
      "గోడల వద్ద 1 అడుగు దూరంలో రంధ్రాలు వేసి కెమికల్ ఇంజెక్షన్",
      "చెదలు వ్యాపించకుండా కెమికల్ బారియర్ ఏర్పాటు",
      "రంధ్రాలను వైట్ సిమెంట్‌తో భద్రంగా మూసివేయడం",
      "1 సంవత్సరం వారంటీ",
    ],
    imageSrc: "/images/termite-banner.jpg",
    category: "pest",
    subcategory: "termite",
  },
  {
    id: "pest-termite-bungalow",
    titleEn: "Bungalow termite control",
    titleTe: "బంగ్లా / విల్లా చెదలు నివారణ (పూర్తి రక్షణ)",
    price: 7999,
    originalPrice: 9999,
    durationEn: "3 hrs 30 mins",
    durationTe: "3 గంటల 30 నిమిషాలు",
    rating: "4.84",
    reviews: "772",
    optionsCount: "4 options",
    inclusionsEn: [
      "Extensive termite protection for larger areas (2000-4000+ sq.ft.)",
      "Covers wooden doors, wardrobes, skirting, and wall perimeters",
      "Detailed drilling, high-pressure chemical injection & white cement application",
      "Long-term warranty with free annual inspection",
    ],
    inclusionsTe: [
      "పెద్ద ఇళ్ళు, బంగ్లాలు మరియు విల్లాల కోసం పూర్తి చెదలు రక్షణ",
      "చెక్క తలుపులు, అల్మారాలు మరియు గోడల మూలల రక్షణ",
      "హై-ప్రెజర్ కెమికల్ ఇంజెక్షన్ మరియు వైట్ సిమెంట్ సీలింగ్",
      "వార్షిక ఉచిత తనిఖీ వారంటీ",
    ],
    imageSrc: "/images/service-pest-termite.jpg",
    category: "pest",
    subcategory: "termite",
  },

  // ANTS & BED BUGS (Screenshots: 2-visit bed bugs, Ant control)
  {
    id: "pest-bedbugs-2visit",
    titleEn: "Bed bugs control",
    titleTe: "నల్లుల నిర్మూలన (2-విజిట్ పద్ధతి)",
    price: 1899,
    originalPrice: 2299,
    durationEn: "1 hr 30 mins",
    durationTe: "1 గంట 30 నిమిషాలు",
    rating: "4.77",
    reviews: "40k",
    optionsCount: "5 options",
    inclusionsEn: [
      "Essential pre-service inspection of the entire home and beds",
      "Unique 2-visit treatment to target eggs, nymphs & adult bedbugs",
      "High-penetration misting on mattress seams, bed frames, and baseboards",
      "45-day warranty with free follow-up visit",
    ],
    inclusionsTe: [
      "ఇల్లు, పరుపులు & మంచాల పూర్తి తనిఖీ",
      "గుడ్లు, పిల్ల మరియు పెద్ద నల్లులను చంపే 2-విజిట్ పద్ధతి",
      "పరుపుల అంచులు, మంచం ఫ్రేములపై ప్రత్యేక స్ప్రే",
      "45 రోజుల వారంటీ",
    ],
    imageSrc: "/images/service-pest-bedbug.jpg",
    category: "pest",
    subcategory: "bedbugs-ants",
  },
  {
    id: "pest-ant-apartment-without-utensils",
    titleEn: "Apartment ant control (without utensil removal)",
    titleTe: "అపార్ట్‌మెంట్ చీమల నివారణ",
    price: 1549,
    originalPrice: 1799,
    durationEn: "45 mins",
    durationTe: "45 నిమిషాలు",
    rating: "4.83",
    reviews: "1k",
    optionsCount: "5 options",
    inclusionsEn: [
      "Complete ant treatment for confined spaces",
      "Targeted odorless baiting along ant trails and wall cracks",
      "30-day warranty",
    ],
    inclusionsTe: [
      "చీమలు నడిచే దారులు మరియు గోడ పగుళ్లలో వాసన లేని మందులు",
      "సామాన్లు తీయకుండా సురక్షితమైన చికిత్స",
      "30 రోజుల వారంటీ",
    ],
    imageSrc: "/images/service-pest-general.jpg",
    category: "pest",
    subcategory: "bedbugs-ants",
  },
  {
    id: "pest-ant-kitchen-bathroom",
    titleEn: "Ant control – kitchen/bathroom (without utensil removal)",
    titleTe: "వంటగది & బాత్‌రూమ్ చీమల నివారణ",
    price: 998,
    originalPrice: 1199,
    durationEn: "30 mins",
    durationTe: "30 నిమిషాలు",
    rating: "4.87",
    reviews: "813",
    optionsCount: "6 options",
    inclusionsEn: [
      "Targeted kitchen platform and drain pipe ant elimination",
      "Safe herbal gel dots inside cabinets and shelves",
      "30-day warranty",
    ],
    inclusionsTe: [
      "వంటగది ప్లాట్‌ఫారమ్ మరియు డ్రెయిన్ వద్ద చీమల నిర్మూలన",
      "హెర్బల్ సురక్షిత జెల్",
      "30 రోజుల వారంటీ",
    ],
    imageSrc: "/images/service-pest-v2.jpg",
    category: "pest",
    subcategory: "bedbugs-ants",
  },
];

// 3. HOME & BATHROOM CLEANING SUB-CATEGORIES & PACKAGES (Screenshots: Value deals, One time, Mini services)
// 3. HOME, BATHROOM & KITCHEN CLEANING (Exact replication from screenshots with Nellore Market Pricing)
export const BATHROOM_SUBCATEGORIES = [
  { id: "bath-value-deals", labelEn: "Value deals", labelTe: "కాంబో డీల్స్" },
  { id: "bath-one-time", labelEn: "One time deep clean", labelTe: "డీప్ క్లీనింగ్" },
  { id: "bath-mini-services", labelEn: "Mini services", labelTe: "మినీ సర్వీసులు" },
] as const;

export const KITCHEN_SUBCATEGORIES = [
  { id: "kitchen-value-deals", labelEn: "Value deals", labelTe: "కాంబో డీల్స్" },
  { id: "kitchen-chimney-stove", labelEn: "Chimney & Stove", labelTe: "చిమ్నీ & పొయ్యి" },
  { id: "kitchen-appliances", labelEn: "Appliance clean", labelTe: "ఉపకరణాల క్లీనింగ్" },
  { id: "kitchen-cabinets-mini", labelEn: "Cabinets & Mini", labelTe: "కేబినెట్స్ & మినీ" },
] as const;

export const CLEANING_SUBCATEGORIES = [
  { id: "value-deals", labelEn: "Value Deals", labelTe: "కాంబో డీల్స్" },
  { id: "one-time", labelEn: "One Time Deep Clean", labelTe: "డీప్ క్లీనింగ్" },
  { id: "mini-services", labelEn: "Mini Services", labelTe: "మినీ సర్వీసులు" },
] as const;

// --- BATHROOM CLEANING CATALOG (Screenshot 2: Value deals, One time deep clean, Mini services) ---
export const BATHROOM_SERVICE_ITEMS: UCServiceItemData[] = [
  // Value deals (Screenshot 2)
  {
    id: "clean-bath-4pack",
    titleEn: "Intense cleaning (4 bathrooms)",
    titleTe: "ఇంటెన్స్ బాత్‌రూమ్ క్లీనింగ్ (4 బాత్‌రూమ్‌లు)",
    price: 1699,
    originalPrice: 2100,
    durationEn: "4 hrs",
    durationTe: "4 గంటలు",
    rating: "4.84",
    reviews: "7.2k",
    optionsCount: "₹425/bathroom",
    badge: "Best Value",
    inclusionsEn: [
      "Floor & tile machine scrubbing with handheld rotary polisher",
      "Hard water scale & yellow stain removal from wall tiles",
      "Toilet pot descaling, chrome fixture polishing & mirror buffing",
      "4 bathrooms deep cleaned simultaneously by verified pros",
    ],
    inclusionsTe: [
      "హ్యాండ్‌హెల్డ్ మెషిన్‌తో ఫ్లోర్ & టైల్స్ స్క్రబ్బింగ్",
      "టైల్స్‌పై గార మరియు ఉప్పు నీటి మరకల తొలగింపు",
      "టాయిలెట్ పాట్, ట్యాప్‌లు మరియు అద్దాల మెరుపు క్లీనింగ్",
      "4 బాత్‌రూమ్‌లకు అత్యుత్తమ నెల్లూరు ప్యాకేజీ (₹425/బాత్‌రూమ్)",
    ],
    imageSrc: "/images/service-bath-4pack.jpg",
    category: "cleaning",
    subcategory: "bath-value-deals",
  },
  {
    id: "clean-bath-3pack",
    titleEn: "Intense cleaning (3 bathrooms)",
    titleTe: "ఇంటెన్స్ బాత్‌రూమ్ క్లీనింగ్ (3 బాత్‌రూమ్‌లు)",
    price: 1299,
    originalPrice: 1600,
    durationEn: "3 hrs",
    durationTe: "3 గంటలు",
    rating: "4.84",
    reviews: "7.2k",
    optionsCount: "₹433/bathroom",
    inclusionsEn: [
      "Floor & tile cleaning with rotary scrub machine for 3 bathrooms",
      "Acid-free deep chemical descaling",
      "Chrome fixtures, washbasin, and vanity mirrors buffed",
    ],
    inclusionsTe: [
      "3 బాత్‌రూమ్‌లకు మెషిన్ స్క్రబ్బింగ్ & డీప్ క్లీనింగ్",
      "యాసిడ్ లేని సురక్షిత కెమికల్స్‌తో గార తొలగింపు",
      "ట్యాప్‌లు, వాష్‌బేసిన్ మరియు మిర్రర్ పాలిషింగ్",
    ],
    imageSrc: "/images/service-bath-3pack.jpg",
    category: "cleaning",
    subcategory: "bath-value-deals",
  },
  {
    id: "clean-bath-2pack",
    titleEn: "Intense cleaning (2 bathrooms)",
    titleTe: "ఇంటెన్స్ బాత్‌రూమ్ క్లీనింగ్ (2 బాత్‌రూమ్‌లు)",
    price: 899,
    originalPrice: 1100,
    durationEn: "2 hrs",
    durationTe: "2 గంటలు",
    rating: "4.84",
    reviews: "7.2k",
    optionsCount: "₹449/bathroom",
    badge: "Popular Combo",
    inclusionsEn: [
      "Floor & tile cleaning with rotary scrub machine for 2 bathrooms",
      "Complete water closet and health faucet sanitization",
      "Grout scrubbing and cobweb removal",
    ],
    inclusionsTe: [
      "2 బాత్‌రూమ్‌లకు సమగ్ర మెషిన్ స్క్రబ్",
      "కమోడ్ మరియు హెల్త్ ఫాసెట్ శానిటైజేషన్",
      "టైల్స్ మధ్య మురికి తొలగింపు",
    ],
    imageSrc: "/images/service-bath-2pack.jpg",
    category: "cleaning",
    subcategory: "bath-value-deals",
  },
  {
    id: "clean-bath-fan-pack",
    titleEn: "Intense Bathroom & ceiling fan cleaning (pack of 2)",
    titleTe: "2 బాత్‌రూమ్‌లు + సీలింగ్ ఫ్యాన్ల క్లీనింగ్ ప్యాక్",
    price: 999,
    originalPrice: 1200,
    durationEn: "2 hrs 20 mins",
    durationTe: "2 గంటల 20 నిమిషాలు",
    rating: "4.83",
    reviews: "3.4k",
    inclusionsEn: [
      "Includes 2 intense bathrooms & 2 ceiling fans cleaning",
      "Blade degreasing and dry dusting",
      "Complete bathroom rotary machine scrub",
    ],
    inclusionsTe: [
      "2 బాత్‌రూమ్‌లు మరియు 2 సీలింగ్ ఫ్యాన్ల పూర్తి క్లీనింగ్",
      "ఫ్యాన్ బ్లేడ్ల జిడ్డు తొలగింపు",
    ],
    imageSrc: "/images/service-bath-fan-pack.jpg",
    category: "cleaning",
    subcategory: "bath-value-deals",
  },

  // One time deep clean (Screenshot 2)
  {
    id: "clean-bath-single-intense",
    titleEn: "Intense bathroom cleaning",
    titleTe: "ఇంటెన్స్ బాత్‌రూమ్ డీప్ స్క్రబ్ (1 బాత్రూమ్)",
    price: 449,
    originalPrice: 549,
    durationEn: "50 mins",
    durationTe: "50 నిమిషాలు",
    rating: "4.84",
    reviews: "7.8M",
    optionsCount: "₹449/bathroom",
    badge: "Popular",
    inclusionsEn: [
      "Floor & tile cleaning with rotary scrubbing machine",
      "Recommended for deep cleaning and tough hard-water stains",
      "Toilet bowl descaling inside & out",
      "Washbasin, vanity mirror & chrome tap polishing",
    ],
    inclusionsTe: [
      "మెషిన్‌తో ఫ్లోర్ & టైల్స్ స్క్రబ్బింగ్",
      "మొండి ఉప్పు నీటి మరకలు మరియు గార తొలగింపు",
      "టాయిలెట్ బౌల్ లోపల మరియు బయట శుభ్రం చేయడం",
      "వాష్‌బేసిన్ మరియు మిర్రర్ పాలిషింగ్",
    ],
    imageSrc: "/images/bathroom-scrub-banner.jpg",
    category: "cleaning",
    subcategory: "bath-one-time",
  },
  {
    id: "clean-bath-move-in",
    titleEn: "Move-in bathroom cleaning",
    titleTe: "కొత్త ఇంటి బాత్‌రూమ్ డీప్ క్లీన్",
    price: 599,
    originalPrice: 749,
    durationEn: "1 hr 10 mins",
    durationTe: "1 గంట 10 నిమిషాలు",
    rating: "4.82",
    reviews: "1.2M",
    badge: "Extra 20 mins",
    inclusionsEn: [
      "Extra 20 mins of machine scrubbing of floor and tiles",
      "Recommended before moving into a new or unused bathroom",
      "Removal of construction cement stains and paint splashes",
      "Complete hospital-grade sanitization",
    ],
    inclusionsTe: [
      "అదనంగా 20 నిమిషాల తీవ్రమైన మెషిన్ స్క్రబ్బింగ్",
      "కొత్త ఇళ్లకు మారే ముందు తప్పనిసరి సర్వీస్",
      "సిమెంట్ మరకలు, పెయింట్ చుక్కల తొలగింపు",
    ],
    imageSrc: "/images/service-bath-movein.jpg",
    category: "cleaning",
    subcategory: "bath-one-time",
  },

  // Mini services (Screenshot 2)
  {
    id: "clean-mini-exhaust-fan",
    titleEn: "Bathroom exhaust fan cleaning (additional)",
    titleTe: "బాత్‌రూమ్ ఎగ్జాస్ట్ ఫ్యాన్ క్లీనింగ్",
    price: 99,
    originalPrice: 140,
    durationEn: "15 mins",
    durationTe: "15 నిమిషాలు",
    rating: "4.72",
    reviews: "3.8k",
    inclusionsEn: [
      "Fan blades and outer mesh degreased and cleaned",
      "Additional; one fan is already covered in bathroom service",
    ],
    inclusionsTe: ["ఫ్యాన్ బ్లేడ్ల జిడ్డు మరియు దుమ్ము తొలగింపు"],
    imageSrc: "/images/service-exhaust-fan.jpg",
    category: "cleaning",
    subcategory: "bath-mini-services",
  },
  {
    id: "clean-mini-door",
    titleEn: "Door cleaning (upto 1)",
    titleTe: "తలుపు క్లీనింగ్ (1 తలుపు)",
    price: 49,
    originalPrice: 80,
    durationEn: "10 mins",
    durationTe: "10 నిమిషాలు",
    rating: "4.71",
    reviews: "860",
    inclusionsEn: ["Front and back surface wipe down and handle polishing"],
    inclusionsTe: ["తలుపు ఉపరితలం మరియు హ్యాండిల్ శుభ్రం చేయడం"],
    imageSrc: "/images/service-bathroom-door.jpg",
    category: "cleaning",
    subcategory: "bath-mini-services",
  },
  {
    id: "clean-mini-mirror",
    titleEn: "Mirror cleaning (upto 1)",
    titleTe: "అద్దం క్లీనింగ్ (1 అద్దం)",
    price: 39,
    originalPrice: 60,
    durationEn: "10 mins",
    durationTe: "10 నిమిషాలు",
    rating: "4.83",
    reviews: "520",
    inclusionsEn: ["Streak-free glass cleaner spray and microfiber buffing"],
    inclusionsTe: ["మైక్రోఫైబర్ క్లాత్‌తో అద్దం మెరుపు క్లీనింగ్"],
    imageSrc: "/images/service-bathroom-mirror.jpg",
    category: "cleaning",
    subcategory: "bath-mini-services",
  },
  {
    id: "clean-mini-washbasin",
    titleEn: "Washbasin cleaning (additional)",
    titleTe: "వాష్‌బేసిన్ క్లీనింగ్ (అదనపు బేసిన్)",
    price: 59,
    originalPrice: 90,
    durationEn: "10 mins",
    durationTe: "10 నిమిషాలు",
    rating: "4.80",
    reviews: "1.1k",
    inclusionsEn: ["Chrome tap descaling and ceramic basin stain scrub"],
    inclusionsTe: ["ట్యాప్ మరియు సెరామిక్ బేసిన్ మరకల తొలగింపు"],
    imageSrc: "/images/service-washbasin.jpg",
    category: "cleaning",
    subcategory: "bath-mini-services",
  },
  {
    id: "clean-mini-ceiling-fan",
    titleEn: "Ceiling fan cleaning",
    titleTe: "సీలింగ్ ఫ్యాన్ క్లీనింగ్",
    price: 69,
    originalPrice: 100,
    durationEn: "15 mins",
    durationTe: "15 నిమిషాలు",
    rating: "4.81",
    reviews: "920",
    optionsCount: "6 options",
    inclusionsEn: ["Complete fan blade dust removal and wet wipe down"],
    inclusionsTe: ["ఫ్యాన్ బ్లేడ్ల దుమ్ము మరియు మరకల తొలగింపు"],
    imageSrc: "/images/service-ceiling-fan.jpg",
    category: "cleaning",
    subcategory: "bath-mini-services",
  },
  {
    id: "clean-mini-disinfection",
    titleEn: "Bathroom disinfection",
    titleTe: "బాత్‌రూమ్ డిస్‌ఇన్‌ఫెక్షన్",
    price: 89,
    originalPrice: 130,
    durationEn: "15 mins",
    durationTe: "15 నిమిషాలు",
    rating: "4.85",
    reviews: "2.1k",
    inclusionsEn: ["Complete antibacterial sanitizing spray on all high-touch surfaces"],
    inclusionsTe: ["హై-టచ్ ప్రదేశాలలో యాంటీ బాక్టీరియల్ శానిటైజింగ్ స్ప్రే"],
    imageSrc: "/images/service-bathroom-disinfect.jpg",
    category: "cleaning",
    subcategory: "bath-mini-services",
  },
];

// --- KITCHEN CLEANING CATALOG (Screenshot 1: Value deals, Chimney & Stove, Appliances, Cabinets & Mini) ---
export const KITCHEN_SERVICE_ITEMS: UCServiceItemData[] = [
  // Value deals (Screenshot 1)
  {
    id: "clean-kitchen-chimney-stove",
    titleEn: "Regular chimney & stove cleaning",
    titleTe: "చిమ్నీ & గ్యాస్ స్టవ్ డీప్ క్లీనింగ్ కాంబో",
    price: 649,
    originalPrice: 799,
    durationEn: "1 hr",
    durationTe: "1 గంట",
    rating: "4.81",
    reviews: "1.4M",
    badge: "Bestseller",
    inclusionsEn: [
      "Complete degreasing of outer chimney hood body & baffle filters",
      "Heavy chemical dip to dissolve sticky oil & grease accumulation",
      "Gas stove burners, drip trays, dials and knobs cleaned",
      "Sparkling oil-free finish with zero wall splatter",
    ],
    inclusionsTe: [
      "చిమ్నీ బాడీ మరియు ఫిల్టర్ల నూనె జిడ్డు తొలగింపు",
      "ప్రత్యేక డిగ్రీజర్‌తో జిడ్డు కరిగించడం",
      "గ్యాస్ స్టవ్ బర్నర్లు, ట్రేలు & నాబ్‌ల క్లీనింగ్",
      "గోడలపై మరకలు లేకుండా శుభ్రమైన ముగింపు",
    ],
    imageSrc: "/images/service-cleaning-chimney.jpg",
    category: "cleaning",
    subcategory: "kitchen-value-deals",
  },
  {
    id: "clean-kitchen-sink-slab",
    titleEn: "Kitchen sink & slab deep clean",
    titleTe: "కిచెన్ సింక్ & స్లాబ్ డీప్ క్లీన్",
    price: 399,
    originalPrice: 499,
    durationEn: "45 mins",
    durationTe: "45 నిమిషాలు",
    rating: "4.82",
    reviews: "890k",
    badge: "Popular",
    inclusionsEn: [
      "Hard turmeric & oil stain scrub from granite countertop",
      "Wall backsplash tiles scrubbed with non-abrasive chemical",
      "Stainless steel sink descaling & tap shine polish",
      "Drain mouth disinfected to prevent bad smells",
    ],
    inclusionsTe: [
      "గ్యాస్ బండపై నూనె మరియు పసుపు మరకల తొలగింపు",
      "గోడ టైల్స్ స్క్రబ్బింగ్ మరియు మురికి తొలగింపు",
      "స్టీల్ సింక్ మరకలు పోగొట్టి ట్యాప్ మెరుపు పాలిష్",
      "డ్రెయిన్ శానిటైజేషన్",
    ],
    imageSrc: "/images/service-cleaning-counter.jpg",
    category: "cleaning",
    subcategory: "kitchen-value-deals",
  },
  {
    id: "clean-kitchen-full-deep",
    titleEn: "Complete kitchen deep clean",
    titleTe: "సంపూర్ణ కిచెన్ డీప్ క్లీనింగ్",
    price: 1249,
    originalPrice: 1499,
    durationEn: "2 hrs 30 mins",
    durationTe: "2 గంటల 30 నిమిషాలు",
    rating: "4.84",
    reviews: "2.1M",
    badge: "Full Kitchen",
    inclusionsEn: [
      "All kitchen cabinets & modular drawers wiped inside & out",
      "Chimney exterior, gas stove, and exhaust fan degreased",
      "Countertop, wall tiles, and sink scrubbed & polished",
      "Kitchen floor machine buffed with heavy-duty degreaser",
    ],
    inclusionsTe: [
      "కిచెన్ కేబినెట్లు & డ్రాయర్లు లోపల మరియు బయట క్లీనింగ్",
      "చిమ్నీ, గ్యాస్ స్టవ్ మరియు ఎగ్జాస్ట్ ఫ్యాన్ జిడ్డు తొలగింపు",
      "స్లాబ్, గోడ టైల్స్ మరియు సింక్ డీప్ క్లీనింగ్",
      "కిచెన్ ఫ్లోర్ మెషిన్ స్క్రబ్బింగ్",
    ],
    imageSrc: "/images/kitchen-after.jpg",
    category: "cleaning",
    subcategory: "kitchen-value-deals",
  },

  // Chimney & Stove (Screenshot 1)
  {
    id: "clean-kitchen-autoclean-chimney",
    titleEn: "Auto-clean chimney service",
    titleTe: "ఆటో-క్లీన్ చిమ్నీ సర్వీస్",
    price: 499,
    originalPrice: 649,
    durationEn: "45 mins",
    durationTe: "45 నిమిషాలు",
    rating: "4.79",
    reviews: "450k",
    inclusionsEn: [
      "Oil collector tray emptied and thoroughly degreased",
      "Suction chamber and blower fan blades wiped",
      "Stainless steel/glass hood exterior buffed",
    ],
    inclusionsTe: [
      "ఆయిల్ కలెక్టర్ ట్రే ఖాళీ చేసి డీగ్రీస్ చేయడం",
      "సక్షన్ చాంబర్ మరియు బ్లోవర్ ఫ్యాన్ క్లీనింగ్",
      "చిమ్నీ హుడ్ పాలిషింగ్",
    ],
    imageSrc: "/images/service-cleaning-chimney.jpg",
    category: "cleaning",
    subcategory: "kitchen-chimney-stove",
  },
  {
    id: "clean-kitchen-stove-hob",
    titleEn: "Gas stove & Hob deep degrease",
    titleTe: "గ్యాస్ స్టవ్ & హాబ్ డీప్ డిగ్రీస్",
    price: 299,
    originalPrice: 399,
    durationEn: "35 mins",
    durationTe: "35 నిమిషాలు",
    rating: "4.83",
    reviews: "620k",
    optionsCount: "2, 3, or 4 burners",
    inclusionsEn: [
      "Brass burner rings soaked to clear clogged gas holes",
      "Toughened glass or steel cooktop carbon crust removal",
      "Pan support grills & control knobs soaked and wiped",
    ],
    inclusionsTe: [
      "ఇత్తడి బర్నర్ రంధ్రాలు క్లియర్ చేయడం",
      "గాజు లేదా స్టీల్ హాబ్ పై మాడిన మరకల తొలగింపు",
      "స్టవ్ గ్రిల్స్ మరియు నాబ్స్ క్లీనింగ్",
    ],
    imageSrc: "/images/service-cleaning-stove.jpg",
    category: "cleaning",
    subcategory: "kitchen-chimney-stove",
  },

  // Appliance clean (Screenshot 1)
  {
    id: "clean-kitchen-fridge",
    titleEn: "Refrigerator deep clean (Interior & Exterior)",
    titleTe: "ఫ్రిడ్జ్ సమగ్ర డీప్ క్లీనింగ్ (లోపల & బయట)",
    price: 349,
    originalPrice: 449,
    durationEn: "45 mins",
    durationTe: "45 నిమిషాలు",
    rating: "4.80",
    reviews: "780k",
    badge: "Food Safe",
    inclusionsEn: [
      "All shelves, door pockets & vegetable crisper washed",
      "Interior walls sanitized with food-grade antibacterial spray",
      "Rubber door gasket de-molded and wiped clean",
      "Exterior door surface and handle polished",
    ],
    inclusionsTe: [
      "ఫ్రిడ్జ్ అద్దాల రాక్స్ మరియు కూరగాయల బాక్సులు కడగడం",
      "ఆహారానికి సురక్షితమైన యాంటీ-బాక్టీరియల్ శానిటైజర్",
      "డోర్ రబ్బర్ బీడింగ్ బూజు తొలగింపు",
      "ఫ్రిడ్జ్ వెలుపలి బాడీ మెరుపు పాలిష్",
    ],
    imageSrc: "/images/service-cleaning-fridge.jpg",
    category: "cleaning",
    subcategory: "kitchen-appliances",
  },
  {
    id: "clean-kitchen-microwave",
    titleEn: "Microwave / OTG interior clean",
    titleTe: "మైక్రోవేవ్ / ఒవెన్ లోపలి క్లీనింగ్",
    price: 199,
    originalPrice: 279,
    durationEn: "25 mins",
    durationTe: "25 నిమిషాలు",
    rating: "4.82",
    reviews: "340k",
    inclusionsEn: [
      "Glass turntable plate washed and degreased",
      "Interior baked grease softened with steam wipe",
      "Odor neutralizing spray applied",
    ],
    inclusionsTe: [
      "టర్న్ టేబుల్ గ్లాస్ ప్లేట్ వాష్",
      "లోపలి మాడిన నూనె మరకలు ఆవిరితో తొలగింపు",
      "వాసన లేని పరిశుభ్రత",
    ],
    imageSrc: "/images/service-microwave.jpg",
    category: "cleaning",
    subcategory: "kitchen-appliances",
  },
  {
    id: "clean-kitchen-exhaust",
    titleEn: "Kitchen exhaust fan degreasing",
    titleTe: "కిచెన్ ఎగ్జాస్ట్ ఫ్యాన్ జిడ్డు తొలగింపు",
    price: 119,
    originalPrice: 160,
    durationEn: "20 mins",
    durationTe: "20 నిమిషాలు",
    rating: "4.76",
    reviews: "510k",
    inclusionsEn: [
      "Heavy oily residue dissolved with alkaline degreaser",
      "Blades and outer louvers wiped clean",
    ],
    inclusionsTe: ["ఎగ్జాస్ట్ ఫ్యాన్ బ్లేడ్లపై మొండి జిడ్డు తొలగింపు"],
    imageSrc: "/images/service-exhaust-fan.jpg",
    category: "cleaning",
    subcategory: "kitchen-appliances",
  },
  {
    id: "clean-kitchen-airfryer",
    titleEn: "Air fryer / Small appliance clean",
    titleTe: "ఎయిర్ ఫ్రైయర్ / చిన్న ఉపకరణాల క్లీన్",
    price: 149,
    originalPrice: 199,
    durationEn: "20 mins",
    durationTe: "20 నిమిషాలు",
    rating: "4.85",
    reviews: "120k",
    inclusionsEn: [
      "Fryer basket, grill mesh, and heating element outer clean",
      "Food oil residues removed safely",
    ],
    inclusionsTe: ["ఎయిర్ ఫ్రైయర్ బాస్కెట్ మరియు గ్రిల్ క్లీనింగ్"],
    imageSrc: "/images/service-airfryer.jpg",
    category: "cleaning",
    subcategory: "kitchen-appliances",
  },
  {
    id: "clean-kitchen-ro-mixer",
    titleEn: "Water purifier (RO) / Mixer exterior wipe",
    titleTe: "RO వాటర్ ప్యూరిఫైయర్ / మిక్సీ క్లీనింగ్",
    price: 79,
    originalPrice: 110,
    durationEn: "15 mins",
    durationTe: "15 నిమిషాలు",
    rating: "4.81",
    reviews: "210k",
    inclusionsEn: ["Exterior casing wiped clean with safe surface spray"],
    inclusionsTe: ["బాడీపై నూనె మరియు దుమ్ము మరకల తొలగింపు"],
    imageSrc: "/images/service-cleaning-counter.jpg",
    category: "cleaning",
    subcategory: "kitchen-appliances",
  },

  // Cabinets & Mini (Screenshot 1)
  {
    id: "clean-kitchen-undersink",
    titleEn: "Under-sink cabinet & organizers deep wipe",
    titleTe: "సింక్ కింద కేబినెట్ డీప్ క్లీన్",
    price: 149,
    originalPrice: 199,
    durationEn: "20 mins",
    durationTe: "20 నిమిషాలు",
    rating: "4.75",
    reviews: "180k",
    inclusionsEn: [
      "Cockroach droppings & moisture stains scrubbed",
      "Disinfectant spray applied inside dark corner cabinet",
    ],
    inclusionsTe: ["సింక్ కింద కేబినెట్ బూజు మరియు మురికి శుభ్రం చేయడం"],
    imageSrc: "/images/service-undersink.jpg",
    category: "cleaning",
    subcategory: "kitchen-cabinets-mini",
  },
  {
    id: "clean-kitchen-cabinets-inside",
    titleEn: "Kitchen trolley & cabinets inside-out",
    titleTe: "కిచెన్ ట్రాలీలు & కేబినెట్స్ పూర్తి క్లీన్",
    price: 399,
    originalPrice: 499,
    durationEn: "45 mins",
    durationTe: "45 నిమిషాలు",
    rating: "4.83",
    reviews: "290k",
    inclusionsEn: [
      "Modular wire baskets and tandem boxes wiped clean",
      "Shelf paper changed and dust vacuumed",
    ],
    inclusionsTe: ["మాడ్యులర్ కిచెన్ బాస్కెట్లు మరియు రాక్స్ లోపల క్లీనింగ్"],
    imageSrc: "/images/service-kitchen-cabinets.jpg",
    category: "cleaning",
    subcategory: "kitchen-cabinets-mini",
  },
  {
    id: "clean-kitchen-floor-scrub",
    titleEn: "Kitchen floor machine scrub",
    titleTe: "కిచెన్ ఫ్లోర్ మెషిన్ స్క్రబ్",
    price: 229,
    originalPrice: 320,
    durationEn: "25 mins",
    durationTe: "25 నిమిషాలు",
    rating: "4.84",
    reviews: "420k",
    inclusionsEn: [
      "Machine rotary scrub to lift slippery oil films from kitchen floor tiles",
      "Grout lines deep cleaned and wiped dry",
    ],
    inclusionsTe: ["జిడ్డుగా మారిన కిచెన్ ఫ్లోర్ టైల్స్‌కు మెషిన్ స్క్రబ్"],
    imageSrc: "/images/service-floor-scrubber.jpg",
    category: "cleaning",
    subcategory: "kitchen-cabinets-mini",
  },
  {
    id: "clean-kitchen-drain-unblock",
    titleEn: "Kitchen sink & drain unblock",
    titleTe: "కిచెన్ సింక్ డ్రెయిన్ క్లీనింగ్",
    price: 79,
    originalPrice: 120,
    durationEn: "15 mins",
    durationTe: "15 నిమిషాలు",
    rating: "4.80",
    reviews: "310k",
    inclusionsEn: [
      "Heavy foaming enzyme flush to dissolve food waste and grease blockages",
      "Eliminates foul sink drain odors",
    ],
    inclusionsTe: ["డ్రెయిన్ పైపులో పేరుకుపోయిన నూనె మరియు ఆహార వ్యర్థాల తొలగింపు"],
    imageSrc: "/images/service-cleaning-counter.jpg",
    category: "cleaning",
    subcategory: "kitchen-cabinets-mini",
  },
  {
    id: "clean-kitchen-window-mesh",
    titleEn: "Kitchen window panes & mesh dusting",
    titleTe: "కిచెన్ కిటికీలు & మెష్ క్లీనింగ్",
    price: 79,
    originalPrice: 110,
    durationEn: "15 mins",
    durationTe: "15 నిమిషాలు",
    rating: "4.78",
    reviews: "190k",
    inclusionsEn: ["Glass panes and wire mosquito mesh degreased with foam spray"],
    inclusionsTe: ["కిటికీ అద్దాలు మరియు మెష్‌పై జిడ్డు తొలగింపు"],
    imageSrc: "/images/service-window-mesh.jpg",
    category: "cleaning",
    subcategory: "kitchen-cabinets-mini",
  },
];

// Unified exports for backward compatibility
export const CLEANING_SERVICE_ITEMS: UCServiceItemData[] = [
  ...BATHROOM_SERVICE_ITEMS,
  ...KITCHEN_SERVICE_ITEMS,
];
